### ISSUE TITLE
Wok Set

### ISSUE THREAD

**Issue by WornisOG** [BrightMH/BrightMH#83]
Hey there I just realized that you are not able to wear Wok Set without any Sundans/Strenght Beads since you missing 29 Statuspoints to wear them.

Is it supposed to be like that? I remember even though you had sundan on and still didnt hit the regular points without the pot you could not wear the item and got bugged.

**Comment by Gr33dyJeW** [comment]
Use sundan or strength bead to equip it and plan your equip types in order to meet requirements when your sundan wears off. It's not like there will be more than few if any people who will hit 152 on official...
And yes, it's supposed to be like that. Dok was somewhat modified since it had same stat requirements as Wolk.
